version: '2'
services:  
   my_node_app:
     image: registry.nextflow.tech/my-node:syukur
     container_name: my_node_app 
     environment:
      - MESSAGE=Hai Kamu, iya kamu
      - PORT=3004
     ports:
      - "3004:3004"
     mem_limit: 200M

